"""empty message

Revision ID: 0ce544e0d3fd
Revises: 6639fd7bf830
Create Date: 2020-03-07 11:49:11.473104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce544e0d3fd'
down_revision = '6639fd7bf830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_name', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('io', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['avatar_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'io')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'avatar_name')
    # ### end Alembic commands ###
