"""empty message

Revision ID: 1104c28d1682
Revises: eec6fc81c554
Create Date: 2020-03-10 22:26:31.882196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1104c28d1682'
down_revision = 'eec6fc81c554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mat_id', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mat_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_mat_id'), 'record', ['mat_id'], unique=False)
    op.create_index(op.f('ix_record_node_id'), 'record', ['node_id'], unique=False)
    op.create_index(op.f('ix_record_score'), 'record', ['score'], unique=False)
    op.create_index(op.f('ix_record_timestamp'), 'record', ['timestamp'], unique=False)
    op.create_index(op.f('ix_record_user_id'), 'record', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_user_id'), table_name='record')
    op.drop_index(op.f('ix_record_timestamp'), table_name='record')
    op.drop_index(op.f('ix_record_score'), table_name='record')
    op.drop_index(op.f('ix_record_node_id'), table_name='record')
    op.drop_index(op.f('ix_record_mat_id'), table_name='record')
    op.drop_table('record')
    # ### end Alembic commands ###
