"""empty message

Revision ID: 13c2aed05d88
Revises: 164068299fae
Create Date: 2020-03-10 18:46:09.200636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13c2aed05d88'
down_revision = '164068299fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_node_name'), 'node', ['name'], unique=False)
    op.drop_index('ix_record_is_test', table_name='record')
    op.drop_column('record', 'is_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('is_test', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_record_is_test', 'record', ['is_test'], unique=False)
    op.drop_index(op.f('ix_node_name'), table_name='node')
    op.drop_column('node', 'name')
    # ### end Alembic commands ###
