"""empty message

Revision ID: 164068299fae
Revises: f68491bab66f
Create Date: 2020-03-09 23:29:24.788874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164068299fae'
down_revision = 'f68491bab66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('tree_file', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domain', 'tree_file')
    # ### end Alembic commands ###
