"""empty message

Revision ID: 1d4fcc80736a
Revises: 99d3f9725bbf
Create Date: 2020-03-08 00:21:36.228400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4fcc80736a'
down_revision = '99d3f9725bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_avatar_name'), 'user', ['avatar_name'], unique=False)
    op.create_index(op.f('ix_user_gender'), 'user', ['gender'], unique=False)
    op.create_index(op.f('ix_user_io'), 'user', ['io'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_io'), table_name='user')
    op.drop_index(op.f('ix_user_gender'), table_name='user')
    op.drop_index(op.f('ix_user_avatar_name'), table_name='user')
    # ### end Alembic commands ###
