"""empty message

Revision ID: 3bf6f028cbae
Revises: 1d4fcc80736a
Create Date: 2020-03-08 00:22:15.924475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf6f028cbae'
down_revision = '1d4fcc80736a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_avatar_name', table_name='user')
    op.drop_index('ix_user_io', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_io', 'user', ['io'], unique=False)
    op.create_index('ix_user_avatar_name', 'user', ['avatar_name'], unique=False)
    # ### end Alembic commands ###
