"""empty message

Revision ID: 6639fd7bf830
Revises: d452baa4bf00
Create Date: 2020-03-06 21:52:37.546533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6639fd7bf830'
down_revision = 'd452baa4bf00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_auth'), 'user', ['auth'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_auth'), table_name='user')
    op.drop_column('user', 'email')
    op.drop_column('user', 'auth')
    # ### end Alembic commands ###
