"""empty message

Revision ID: 85790d3b5eac
Revises: 3bf6f028cbae
Create Date: 2020-03-09 09:30:59.260302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85790d3b5eac'
down_revision = '3bf6f028cbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prev', sa.Integer(), nullable=True),
    sa.Column('test_file', sa.String(length=255), nullable=True),
    sa.Column('doamin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doamin_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_doamin_id'), 'node', ['doamin_id'], unique=False)
    op.create_index(op.f('ix_node_prev'), 'node', ['prev'], unique=False)
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node', sa.Integer(), nullable=True),
    sa.Column('material_file', sa.String(length=255), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_creator_id'), 'material', ['creator_id'], unique=False)
    op.create_index(op.f('ix_material_node'), 'material', ['node'], unique=False)
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_test', sa.Integer(), nullable=True),
    sa.Column('mat_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mat_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_is_test'), 'record', ['is_test'], unique=False)
    op.create_index(op.f('ix_record_mat_id'), 'record', ['mat_id'], unique=False)
    op.create_index(op.f('ix_record_score'), 'record', ['score'], unique=False)
    op.create_index(op.f('ix_record_timestamp'), 'record', ['timestamp'], unique=False)
    op.create_index(op.f('ix_record_user_id'), 'record', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_user_id'), table_name='record')
    op.drop_index(op.f('ix_record_timestamp'), table_name='record')
    op.drop_index(op.f('ix_record_score'), table_name='record')
    op.drop_index(op.f('ix_record_mat_id'), table_name='record')
    op.drop_index(op.f('ix_record_is_test'), table_name='record')
    op.drop_table('record')
    op.drop_index(op.f('ix_material_node'), table_name='material')
    op.drop_index(op.f('ix_material_creator_id'), table_name='material')
    op.drop_table('material')
    op.drop_index(op.f('ix_node_prev'), table_name='node')
    op.drop_index(op.f('ix_node_doamin_id'), table_name='node')
    op.drop_table('node')
    op.drop_table('domain')
    # ### end Alembic commands ###
