"""empty message

Revision ID: f68491bab66f
Revises: 
Create Date: 2020-03-09 23:08:14.802764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68491bab66f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('auth', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('avatar_name', sa.String(length=255), nullable=True),
    sa.Column('io', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_auth'), 'user', ['auth'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_gender'), 'user', ['gender'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_file', sa.String(length=255), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_domain_id'), 'node', ['domain_id'], unique=False)
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prev', sa.Integer(), nullable=True),
    sa.Column('nxt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nxt'], ['node.id'], ),
    sa.ForeignKeyConstraint(['prev'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_nxt'), 'link', ['nxt'], unique=False)
    op.create_index(op.f('ix_link_prev'), 'link', ['prev'], unique=False)
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node', sa.Integer(), nullable=True),
    sa.Column('material_file', sa.String(length=255), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_creator_id'), 'material', ['creator_id'], unique=False)
    op.create_index(op.f('ix_material_node'), 'material', ['node'], unique=False)
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_test', sa.Integer(), nullable=True),
    sa.Column('mat_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mat_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_is_test'), 'record', ['is_test'], unique=False)
    op.create_index(op.f('ix_record_mat_id'), 'record', ['mat_id'], unique=False)
    op.create_index(op.f('ix_record_score'), 'record', ['score'], unique=False)
    op.create_index(op.f('ix_record_timestamp'), 'record', ['timestamp'], unique=False)
    op.create_index(op.f('ix_record_user_id'), 'record', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_user_id'), table_name='record')
    op.drop_index(op.f('ix_record_timestamp'), table_name='record')
    op.drop_index(op.f('ix_record_score'), table_name='record')
    op.drop_index(op.f('ix_record_mat_id'), table_name='record')
    op.drop_index(op.f('ix_record_is_test'), table_name='record')
    op.drop_table('record')
    op.drop_index(op.f('ix_material_node'), table_name='material')
    op.drop_index(op.f('ix_material_creator_id'), table_name='material')
    op.drop_table('material')
    op.drop_index(op.f('ix_link_prev'), table_name='link')
    op.drop_index(op.f('ix_link_nxt'), table_name='link')
    op.drop_table('link')
    op.drop_index(op.f('ix_node_domain_id'), table_name='node')
    op.drop_table('node')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_gender'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_auth'), table_name='user')
    op.drop_table('user')
    op.drop_table('domain')
    # ### end Alembic commands ###
